FROM damianh/dotnet-node:4

RUN curl -sL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip \
    && unzip awscliv2.zip \
    && aws/install \
    && rm -rf awscliv2.zip \
    && rm -rf aws/dist/awscli/examples

RUN curl -fsSL https://get.pulumi.com | sh
RUN export PATH=/root/.pulumi/bin:$PATH

RUN npm install -g typescript