name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build dotnet-core-lts-sdks Docker image
      run: docker build dotnet-core-lts-sdks --tag dotnet-core-lts-sdks:$(date +%s)
    - name: Build dotnet-core-node Docker image
      run: docker build dotnet-core-node --tag dotnet-core-node:$(date +%s)
